@startuml Class diagram
set namespaceSeparator none

class "sentinel_mrhat_cam.App" as App {
  - config : Config
  - logger : Logger
  - camera : ICamera
  - communication : ICommunication
  - system : ISystem
  - rtc : IRTC
  - schedule : Schedule
  - message_creator : MessageCreator
  + start() -> None
  + run() -> None
}

class "sentinel_mrhat_cam.Config" as Config {
  + active : Dict
  + uuid: str
  - list: List
  - path : str
  + get_default_config() -> Dict[str, Any]
  + load() -> None
  + validate_config(new_config) -> None
  + validate_period(period) -> None
  + validate_time_format(new_config) -> None
}

interface "sentinel_mrhat_cam.ICamera" as ICamera {
  + start() -> None
  + capture() -> Optional[np.ndarray]
}

class "sentinel_mrhat_cam.Camera" as Camera {
  - cam : Picamera2
  - quality : int
  - width : int
  - height : int
  + start() -> None
  + capture() -> Optional[np.ndarray]
  - create_base64_image(image_array: Optional[np.ndarray]) -> str
}

class "sentinel_mrhat_cam.Logger" as Logger {
  - filepath : str
  - log_queue : Queue[str]
  - pool : ThreadPool
  - start_event : threading.Event()
  - create_communication_handler() -> None
  + disconnect_communication() -> None
  + emit(record) -> None
  - publish_loop(msg: str, topic: str) -> None
  + start_logging() -> None
  + start_remote_logging() -> None
}

interface "sentinel_mrhat_cam.ICommunication" as ICommunication {
  + connect() -> Any
  + disconnect() -> None
  + send(message: str) -> None
  + is_connected() -> bool
  + init() -> None
}

class "sentinel_mrhat_cam.MQTT" as MQTT {
  - broker : str
  - port : int
  - qos : int
  - subtopic : str
  + client : paho.mqtt.Client
  + config_confirm_message : str
  + config_received_event : Event
  - broker_connect_counter : int
  + connect() -> Any
  + disconnect() -> None
  - publish(message: str, topic: str) -> None
  + send(message: str) -> None
  + is_connected() -> bool
  - broker_check() -> None
  + init_receive() -> None
  - is_broker_available() -> bool
  + reset_config_received_event() -> None
}

class "sentinel_mrhat_cam.Schedule" as Schedule {
  - time_offset : int
  + adjust_time(timestamp: str) -> str
  + calculate_shutdown_duration(waiting_time: float) -> float
  + get_wake_time(shutdown_duration: float) -> datetime
  + should_shutdown(waiting_time: float) -> bool
  + shutdown(waiting_time: float, current_time: datetime) -> None
  + working_time_check(wake_up_timestamp: str, shut_down_timestamp: str) -> None
}

interface "sentinel_mrhat_cam.IRTC" as IRTC {
  + get_time() -> str
}

class "sentinel_mrhat_cam.RTC" as RTC {
  - sync_RTC_to_system() -> None
  - sync_system_to_ntp(max_retries: int, delay: int) -> bool
  + get_time() -> str
  - convert_timestamp(timestamp) -> str
  - get_timedatectl() -> List[str]
  - find_line(lines: str, target_string) -> str
}

interface "sentinel_mrhat_cam.ISystem" as ISystem {
  + schedule_wakeup(wake_time: Union[str, int, float]) -> None
  + get_hardware_info() -> Optional[Dict[str, Any]]
}

class "sentinel_mrhat_cam.System" as System {
  + schedule_wakeup(wake_time: Union[str, int, float]) -> None
  - get_cpu_temperature() -> float
  - get_battery_info() -> Dict[str, Any]
  + get_hardware_info() -> Optional[Dict[str, Any]]
}

class "sentinel_mrhat_cam.MessageCreator" as MessageCreator {
  - system : ISystem
  - rtc : IRTC
  - camera : ICamera
  + create_message() -> str
  + log_hardware_info() -> None
}

App *-- Config
App -- Logger
App *-- Schedule
App *-- MessageCreator
App ..> ICamera
App ..> ICommunication
App ..> ISystem
App ..> IRTC
MessageCreator ..> ISystem
MessageCreator ..> IRTC
MessageCreator ..> ICamera
Logger --> ICommunication
MQTT ..|> ICommunication
RTC ..|> IRTC
System ..|> ISystem
Camera ..|> ICamera
@enduml