name: Test

on:
    push:
      branches: main
      tags-ignore: 'v*.*.*'  # Prevent duplicate runs

    workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcap-dev
      - name: Install packages
        run: pip install .
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Run tests with pytest
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}